# Configuration file for SCT Camera slow control

User Interface:
    host: null
    input_port: null
    output_port: null

fan:
    protocol: telnet
    telnet_host: null
    telnet_port: null
    telnet_timeout: 5

High Level Commands:

    setup_fan:
        args: []
        device_commands:
            -
                device: fan
                command: turn_on
            -
                device: server
                command: sleep
                params: {secs: 3}
            -
                device: fan
                command: read_current
